#include "keymap.h"

std::array<std::array<Key, MATRIX_COLS>, MATRIX_ROWS> matrix =
    {KEYMAP(
KC_A, KC_B, KC_C, KC_D, KC_E, KC_F, KC_G,
KC_H, KC_I, KC_J, KC_K, KC_L, KC_M, KC_N,
KC_O, KC_P, KC_Q, KC_R, KC_S, KC_T, KC_U,
KC_V, KC_W, KC_X, KC_Y, KC_Z, KC_1, KC_2,
KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9,
KC_0, KC_ENT,KC_ESC,KC_TAB,KC_BSPC,KC_INS,KC_DEL,
KC_LEFT,KC_UP,KC_DOWN,KC_RGHT,KC_PGUP,KC_PGDN,KC_HOME,
KC_END,KC_SPC,KC_LSFT,KC_RSFT,KC_LCTL,KC_RCTL,KC_LGUI,
KC_RGUI,KC_LALT,KC_RALT,KC_CAPS,KC_F1,KC_F2,KC_F3,
KC_F4,KC_F5,KC_F6,KC_F7,KC_F8,KC_F9,KC_F10
    )};

void setupKeymap() {}
